name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: format
      run: cargo fmt --all -- --check `find src -iname "*.rs"`
    - name: build
      run: cargo build --verbose --all
    - name: test
      run: cargo test --verbose --all
    - name: lint
      run: cargo clippy --verbose --release -- -D clippy::all
